openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9091"
paths:
  /checkTrains:
    get:
      summary: Useful to check for the available trains from a given station to another
      operationId: getChecktrains
      parameters:
      - name: from
        in: query
        description: Starting station
        required: true
        schema:
          type: string
      - name: to
        in: query
        description: Destination station
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainInfo'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /bookTrain:
    post:
      summary: Useful to book a train given the train ID
      operationId: postBooktrain
      parameters:
      - name: trainScheduleId
        in: query
        description: ID of the train to be booked
        required: true
        schema:
          type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingInfo'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /getTrain:
    get:
      summary: Useful to get the details of a train given the train ID
      operationId: getGettrain
      parameters:
      - name: trainScheduleId
        in: query
        description: ID of the train to be retrieved
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  train:
                    $ref: '#/components/schemas/TrainInfo'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /getTrains:
    get:
      summary: Useful to get the details of all the trains
      operationId: getGettrains
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainInfo'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /getTrainsByType:
    get:
      summary: Useful to get the details of all the trains of a given type
      operationId: getGettrainsbytype
      parameters:
      - name: trainType
        in: query
        description: Type of the train to be retrieved
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainInfo'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /getTrainsByTime:
    get:
      summary: Useful to get the details of all the trains of a given time
      operationId: getGettrainsbytime
      parameters:
      - name: startTime
        in: query
        description: Starting time of the train
        required: true
        schema:
          type: string
      - name: endTime
        in: query
        description: Ending time of the train
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainInfo'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    TrainInfo:
      required:
      - endTime
      - entryId
      - from
      - startTime
      - to
      - trainType
      type: object
      properties:
        entryId:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        from:
          type: string
        to:
          type: string
        trainType:
          type: string
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    BookingInfo:
      required:
      - bookingId
      - endTime
      - from
      - startTime
      - to
      - trainType
      type: object
      properties:
        bookingId:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        from:
          type: string
        to:
          type: string
        trainType:
          type: string
